swagger: '2.0'
info:
  version: 1.0.0
  title: LecAnibal API
host: LecAnibal.com
basePath: /customer/api/v1
tags:
  - name: User
    description: Everything about your Users

paths:
  /user/login:
    post:
      tags:
        - User
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/login'
      responses:
        '405':
          description: Invalid input
        '200':
          description: login

securityDefinitions:
  JWT:
    type: apiKey
    in: header
    name: access_token

definitions:
  login:
    type: object
    properties:
      user:
        type: string
      password:
        type: string
